version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - app-data:/app-data
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    driver: local
  app-data:
    driver: local
